### ISSUE TITLE
code mistake

### ISSUE THREAD

**Issue by SaintLogos1234** [jireh-father/tensorflow-alexnet#2]
Traceback (most recent call last):
  File "kaggle_mnist_alexnet.py", line 155, in <module>
    tf.app.run()
  File "/home/xieyangyang/anaconda3/envs/tensorflow1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "kaggle_mnist_alexnet.py", line 149, in main
    train()
  File "kaggle_mnist_alexnet.py", line 58, in train
    FLAGS.validation_size, FLAGS.batch_size)
  File "/home/xieyangyang/Tensorflow/day8/tensorflow-alexnet-master/kaggle_mnist_input.py", line 36, in load_mnist_train
    labels_flat = data[[0]].values.ravel()
  File "/home/xieyangyang/anaconda3/envs/tensorflow1/lib/python2.7/site-packages/pandas/core/frame.py", line 2682, in __getitem__
    return self._getitem_array(key)
  File "/home/xieyangyang/anaconda3/envs/tensorflow1/lib/python2.7/site-packages/pandas/core/frame.py", line 2726, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/home/xieyangyang/anaconda3/envs/tensorflow1/lib/python2.7/site-packages/pandas/core/indexing.py", line 1327, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: '[0] not in index'

The requested URL /dl/teset.csv was not found on this server.

**Comment by SaintLogos1234** [comment]
Sorry, I don't look the Pull requests, the problems is solved, Thank you
